### ISSUE TITLE
How to view the crestron hardware information (cpu, memory, etc.)

### ISSUE THREAD

**Issue by songzh96** [akellai/Crestron-KNX#1]
Hi akellai，
Your project is very good. It's very helpful to me.
Can you tell me how to access this information? 
I want to put that information on a platform and monitor it.

Best regards

**Comment by akellai** [comment]
Not sure if I understood the question. Have you tried using System Monitor from the Crestron Toolbox?

**Comment by songzh96** [comment]
Emmmm, sorry my english is pool.

I want to know  how to get some host information in crestron.(Crestron API)
do you know that?
Thank you

**Comment by akellai** [comment]
if you want to do that within SIMPL/SIMPL#, some answers are below:
- for the HW you don't have to do anything as you should know the exact HW during compile
- For the memory the CrestronEnvironment.SystemInfo class should help
- For the CPU I don't see anything in the SimplSharp namespace, but if you do SimplSharpPro, look at the Crestron.SimplSharpPro.Diagnostics namespace

**Comment by akellai** [comment]
not related to the project
