### ISSUE TITLE
Can't write messages to KNX BUS

### ISSUE THREAD

**Issue by songzh96** [akellai/Crestron-KNX#6]
Hi @akellai 

When I use the plugin, I found a strange problem
I can listen to messages on the KNX bus, but I cannot write messages to the KNX bus.

When I restarted my gateway, It was able to write again.
What can I do to get some debugging information

KNX-IP GateWay ： Raspberry+KNXD

Best Regards
Songzh

**Comment by akellai** [comment]
my recommendations:
- use the latest knxd (I follow the github and the bugs for usb knx devices are still coming)
- use "0.0.0" as MyKnxAddress in the KnxTunnel module - this will make sure knxd auto assigns the address as appropriate

As far as the debugging goes, I cannot recommend anything specific. I myself would probably use tcpdump on rpi and see if the packets are coming from the crestron

Thanks,
akellai

**Comment by songzh96** [comment]
thank you very much
I will try it

Best Regards
Songzh

**Comment by songzh96** [comment]
Hi

I now have a strange problem
KnxTunnel Model Unable to link
ETS can connect KNX-IP
But When I use RPI to ping Crestron AV3, can ping it, use AV3 to ping RPI, also can.

AV3:192.168.10.230
RPI:192.168.10.234
KNXD_OPTS="-n HEARTKNX -e 0.0.1 -E 0.0.2:8 -u /tmp/eib -DTS -b tpuarts:/dev/ttyAMA0"

![image](https://user-images.githubusercontent.com/26770241/82855503-0f32d600-9f3e-11ea-951b-73d1c4408c96.png)
![image](https://user-images.githubusercontent.com/26770241/82855507-122dc680-9f3e-11ea-99f6-1d04f3ae824c.png)


I don't know where the problem is，but I think it ’s the network that bans multicast.

Best Regards
Songzh

**Comment by songzh96** [comment]
I think the new firmware blocks KNX.Net SIMPL #. 
I have n’t been able to link since I updated the firmware

**Comment by akellai** [comment]
Can the module connect? Does KNX_Connected goes high?
Also does debug show you any activity when you set KNX_DEBUG to 1?

**Comment by songzh96** [comment]
nope

I think it is crestron firmware problem.
Because I could use it before upgrading the firmware，But I ca n’t use it after upgrading the firmware.
I suspect that Crestron closed the 3671 port，But I do n’t know how to confirm.

yes, i set debug is 1, but no msg output.
It is best not to upgrade the firmware

**Comment by akellai** [comment]
I would be surprised if new firmware disables any udp ports. This would break lots of other Crestron functionality. Can you may be reset your controller to defaults and re-download the program?

**Comment by songzh96** [comment]
Hi
I ’m pretty sure it ’s a firmware issue, because I ’ve tested it on two projects.

I am currently on a business trip without environmental testing, when I get home I will test it according to what you said

**Comment by songzh96** [comment]
There are currently some bugs in Crestron

The Crestron software I use is the latest software. After I upload the program, many macros will be invalid. These macros will not work until I update the host firmware.

But the KNX Tunnel Module has never been able to connect to my KNX-IP gateway.

**Comment by akellai** [comment]
I see what you mean. It's not firmware, but rather new SIMPL for Windows and/or crestron database that break it. I've updated to the latest and see lots of exceptions like:

392. Error: splusmanagerapp.exe [App 2] # 2020-06-02 01:53:13  # Module S-2.1 : KnxTunnel at line 107: Unhandled Exception: System.MethodAccessException: MethodAccessException
   at UserModule_KNXTUNNEL.UserModuleClass_KNXTUNNEL.CONNECT_OnPush_0(Object __EventInfo__)
   at Amib.Threading.Internal.WorkItem.ExecuteWork393. Error: splusmanagerapp.exe [App 2] # 2020-06-02 01:53:13  # Item()
   at Amib.Threading.Internal.WorkItem.Execute()
   at Amib.Threading.SmartThreadPool.ExecuteWorkItem(WorkItem workItem)
   at Amib.Threading.SmartThreadPool.ProcessQueuedItems()
in the error log.

Should be easily fixable, give me a couple of days

**Comment by akellai** [comment]
Should be fixed in the latest commit (compatibility with Crestron SIMPL for Windows 4.14.20)

**Comment by songzh96** [comment]
OK， Thanks
 I will test it tomorrow，😀

Best Regards
Songzh
