### ISSUE TITLE
Cuts addresses more than 16/0/0 

### ISSUE THREAD

**Issue by yanovik** [akellai/Crestron-KNX#7]
Hello, when the message in ets trace is "18/0/0" for example, it come out of crestron module as "2/0/0". Thank you

**Comment by akellai** [comment]
Should be fixed in the latest commit

**Comment by yanovik** [comment]
Could you plz recompile KnxTunnelSS.clz file?

**Comment by akellai** [comment]
done

**Comment by yanovik** [comment]
Thanks!
