### ISSUE TITLE
Crestron KnX

### ISSUE THREAD

**Issue by arunaj2004** [akellai/Crestron-KNX#8]
Hi when I used the KNX tunnel, I am getting one error. I am using the CP4 processor. I am attaching the debugger screen shot
![WhatsApp Image 2022-03-17 at 11 45 03 AM](https://user-images.githubusercontent.com/53625461/158760999-4cd1e191-eece-4cbe-9049-49cc75dd6d51.jpeg)
.

**Comment by akellai** [comment]
should be fixed long time ago https://github.com/akellai/Crestron-KNX/commit/85d3410692d8f5b926d3e2c7c16e3a4c071ef2bc
please use the latest version
